version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: collabspace-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: CollabSpace
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CollabSpace"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
