version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: collabspace-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: CollabSpace
    ports:
      - "5445:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CollabSpace"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:8.0
    container_name: collabspace-redis
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - collabspace-network
    volumes:
      - redis_data:/data

networks:
  collabspace-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
