server:
  port: 8080
  mode: "development"
  allowedOrigins:
    - "http://localhost:3000"
    - "http://localhost:3001"
  frontendReturnURLWhitelist:
    - "http://localhost:3000/reset-password"
    - "http://localhost:3001/reset-password"

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  dbname: "CollabSpace"
  type: "postgres"

jwt:
  accessTokenDuration: "1h"
  refreshTokenDuration: "168h"

redis:
  host: "localhost"
  port: 6379
  password: ""
